######################################################################
## Configuration file for TekkitRestrict                            ##
## Authors: Taeir, DreadEnd (aka DreadSlicer)                       ##
## BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/    ##
## Please ask questions/report issues on the BukkitDev page.        ##
######################################################################

######################################################################
## Some fast notes for you all. First, every option in this file is ##
## Reloadable. That means that by typing "/tr admin reload" in-game ##
## (with the "tekkitrestrict.admin.reload" permission), or by       ##
## typing "tr admin reload" in the console, you can reload every    ##
## single config change in this file.                               ##
##                                                                  ##
## Have fun, Play safe. Good luck.                                  ##
## * DreadEnd * out.                                                ##
######################################################################
# Add Tekkit Material names (to get the name of the block/item, used
# by logging plugins, Essentials, LWC, etc.) to Bukkit.
AddTekkitMaterialNames: true

# Add Equivalent Exchange items names to the Essentials Item Database
# (used for /i, /give, /itemdb)
AddEEItemsToEssentials: true

# Patch ComputerCraft once to prevent some server crashes with
# ComputerCraft computers.
# Default: true
PatchComputerCraft: true

# Change the lowest possible time for RedPower Timers to the value set
# in ModModifications.config.yml
# Default: true
UseAutoRPTimer: true

# TekkitRestrict has a Limiter. With it, you can set how many of a
# certain block a player may have placed at a time.
# For example, you could limit the amount of collectors Mk. 3 someone
# can have by limiting 126:2 to 1 in the Advanced.config.yml.
#
# This option toggles the use of this limiter on or off.
# Default: true
UseItemLimiter: true

# Should LimitedCreative be enabled?
# Default: true
UseLimitedCreative: true
# If UseOpenAlc is false, the command /openalc will be disabled.
# Default: true
UseOpenAlc: true

# Should TekkitRestricts banned items feature be enabled?
# Default: true
UseNoItem: true

# If KickFromConsole is true, the console will execute the /kick
# command instead of the default Bukkit kick when a player gets
# kicked by TekkitRestrict (e.g. for hacking).
# Useful if you want to log kicks or use a different bansystem.
# Default: false
KickFromConsole: false

######################################################################
############################## Updater ###############################
# Should TekkitRestrict check for an update when the server starts?
# Default: true
CheckForUpdateOnStartup: true

# Should the update be downloaded automatically if there is one?
# Default: true
Auto-Update: true

# Should TekkitRestrict update to beta versions?
# If you are currently running a beta version, this option is ignored.
# Default: false
UpdateToBetaVersions: false

# Should TekkitRestrict update to development versions?
# If you are currently running a dev version, this option is ignored.
# Default: false
UpdateToDevelopmentVersions: false

######################################################################
############################## TMetrics ##############################
# Lately Metrics by Hidendra hasn't been very reliable. The graphs
# show things I can hardly believe. I would like to know how many
# servers actually use TekkitRestrict, what systems they are
# running on and how much memory is dedicated to those servers.
#
# For this reason I decided to make my own metrics system called
# TMetrics.
#
# TMetrics sends the data to http://metrics.taico.nl/, my own website,
# where the data will be stored. Every server will get a unique ID
# that makes sure there will be few to no duplicates in the
# database. This UID is stored in a file in the tekkitrestrict plugin
# directory, and I ask you to never delete it.
#
# TMetrics will send the following information:
# - The version of TekkitRestrict you are using
# - The version of Minecraft you are using
# - If onlinemode is on or off
# - The amount of players online
# - The system you are running the server on
# - If that system is 32 or 64 bit
# - The amount of cores your system has.
# - The amount of memory allocated to your Minecraft server
# - The version of Java you are using
#
# When the server starts, TMetrics will send system data to let
# the server know if something has changed (Memory allocated,
# Operating system, Java version, etc.). After that, TMetrics will
# ping my server every 15 minutes. On these pings it will only send
# the amount of players online.
#
# If you don't want to send these metrics, you can set UseTMetrics
# to false.
UseTMetrics: true

# Should TMetrics give warnings in the console when submitting the
# statistics failed?
ShowTMetricsWarnings: true

######################################################################
######################################################################
# Warning, advanced setting. Don't change this if you don't know what
# kind of impact it will have.
#
# If FavorPerformanceOverMemory is set to true, tekkitrestrict will
# use more RAM, but will use less CPU/do less every tick.
# If you have a lot of RAM that you are not using, it might be best
# to set this to true.
FavorPerformanceOverMemory: false

######################################################################
######################################################################
# Do NOT change this. It will reset the config files if you do.
ConfigVersion: 2.2

######################################################################