###########################################################################
## Configuration file for TekkitRestrict                                 ##
## Authors: Taeir, DreadEnd (aka DreadSlicer)                            ##
## BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/         ##
## Please ask questions/report issues on the BukkitDev page.             ##
###########################################################################

###########################################################################
################################# Logging #################################
###########################################################################

# The format of the name of the logfile.
# Default: "{TYPE}-{DAY}-{MONTH}-{YEAR}.log"
FilenameFormat: "{TYPE}-{DAY}-{MONTH}-{YEAR}.log"

# The format to log a string.
# Default: "[{HOUR}:{MINUTE}:{SECOND}] {INFO}"
LogStringFormat: "[{HOUR}:{MINUTE}:{SECOND}] {INFO}"

# Should debug messages be logged?
# Default: false
LogDebug: false

###########################################################################
################################ Split Logs ###############################
###########################################################################

# Should tekkitrestrict split the logs into many parts?
# (e.g. Chat, Commands, Login/Logout, Warnings, etc.)
# Default: true
SplitLogs: true

# The folder where TekkitRestrict should place the split logs.
# NOTE: The path starts at the server root.
# Example file: server_root/log/chat/chat-23-10-13.log
# Default: "log"
SplitLogsLocation: "log"

###########################################################################
############################### Filter Logs ###############################
###########################################################################

# Should TekkitRestrict filter out certain things from the logs?
# Default: true
FilterLogs: true

# Here you can define the filters.
# There are 5 different methods:
# Contains - If a logmessage contains ...
# StartsWith - If a logmessage starts with ...
# EndsWith - If a logmessage ends with ...
# Equals - If a logmessage is identical to ...
# RegEx - If a logmessage matches ... (please do not use (?i))
#
# There are multiple types
# Console - Filter messages only from the console, NOT the logs
# ServerLog - Filter messages only from the server logs
# ForgeServerLog - Filter messages only from the forge logs
# All - Filter messages everywhere
# Console_ServerLog - Filter messages from the console and server logs
# Forge_ServerLog - Filter messages from forge logs and the server logs
# 
Filters:
    Filter1:
        Method: contains
        CaseSensitive: false
        Type: all
        Messages: []
    SpammyMessages:
        Method: regex
        CaseSensitive: true
        Type: all
        Messages:
        - "Sending Triang: -*\d+, -*\d+\.\d+"
        - "slotChanging\\(\\d+\\)"
    MovedWrongly:
        Method: regex
        CaseSensitive: true
        Type: console
        Messages:
        - "Got position -*\d+\.\d+, -*\d+\.\d+, -*\d+\.\d+"
        - "Expected -*\d+\.\d+, -*\d+\.\d+, -*\d+\.\d+"
    IPLostConnection:
        Method: regex
        CaseSensitive: true
        Type: console_serverlog
        Messages:
        - "/\d+\.\d+\.\d+\.\d+:\d+ lost connection"
    Join1:
        Method: startswith
        CaseSensitive: true
        Type: console_serverlog
        Messages:
        - "Sending serverside check to: "
    Join2:
        Method: contains
        CaseSensitive: true
        Type: console_serverlog
        Messages:
        - " joined with: ["
    ConnectionErrors:
        Method: equals
        CaseSensitive: true
        Type: console_serverlog
        Messages:
        - "Connection reset"
        - "Reached end of stream"
    PurifyConsole:
        Method: equals
        CaseSensitive: true
        Type: console
        Messages:
        - "GroupManager - INFO -  Data files refreshed."


# If a String contains any of the items listed here, it will not be
# logged. Does not work if FilterLogs is false.
# To add loglevels, do the following:
# - "loglevel: fine"
LogFilter:
- "joined with"
- "overloaded?"
- "latest artifact information"
- "repair is active.."
- "player found.."
- "slotchanging("
- "chunk coordinates:"

###########################################################################
############################### Log Enhancer ##############################
###########################################################################
UseLogEnchancer: true
EnchanceEssentialsCmd: true
ChangeGive: true
ShortenErrors: true
EnhanceEssentialsCmdDeny: true
#RemovePlayerTags: false

Reformat:
    Option1:
#        Method: regex
#        CaseSensitive: true
#        M1:
        Message: "\[(.*)\] \[(.*)\] (.*): (.*)"
        Replacement: "\[($2)\] ($3): ($4)"
    

###########################################################################
############################# Log Hacks/Dupes #############################
###########################################################################
# NOTE: These will be logged at plugins/tekkitrestrict/log/

# When a user is FlyHacking, should it be logged?
# Default: true
LogFlyHack: true

# When a user is SpeedHacking, should it be logged?
# Default: true
LogMovementSpeedHack: true

# When a user is ForcefieldHacking, should it be logged?
# Default: true
LogForcefieldHack: true

# When a player (tries to) dupe, should it be logged?
# Default: true
LogDupes: true

###########################################################################
############################## Log EE Items ###############################
###########################################################################
# NOTE: These will be logged at plugins/tekkitrestrict/log/

# When a player uses an amulet, should it be logged?
# Default: true
LogAmulets: true

# When a player uses a ring, should it be logged?
# Default: true
LogRings: true

# When a player uses a Dark Matter Tool, should it be logged?
# Default: true
LogDMTools: true

# When a player uses a Red Matter Tool, should it be logged?
# Default: true
LogRMTools: true

# When a player uses certain EE items, should it be logged?
# Default: true
LogEEMisc: true

# When a player uses a Destructive EE item, should it be logged?
# Default: true
LogEEDestructive: true

###########################################################################
###########################################################################
###########################################################################