##########################################################################################
## Configuration file for TekkitRestrict                                                ##
## Authors: Taeir, DreadEnd (aka DreadSlicer)                                           ##
## BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/                        ##
## Please ask questions/report issues on the BukkitDev page.                            ##
##########################################################################################

##########################################################################################
################################# SafeZone Configuration #################################
##########################################################################################

# Should TekkitRestrict use SafeZones?
# Default: true
UseSafeZones: true

# Note: This will only apply to WorldGuard and GriefPrevention SafeZones, and
#       NOT to Towny, Factions or PreciousStones SafeZones.
InSafeZones:
    # If you turn DisableEntities on, then
    # - No mobs will spawn in SafeZones.
    # - If a mob enters a SafeZone, it is removed.
    # Default: true
    DisableEntities: true
    
    # This is a feature that allows tekkitrestrict to run the entities disabler
    # thread with less lag and problems. Entities can get removed at range blocks
    # from the corner of the safezone.
    #
    # Increase this value if you have problems with the entity remover or if you want
    # to increase performance.
    # Default: 10
    DisableEntitiesRange: 10
    
    # WARNING: Case Sensitive!
    # Tries to exclude org.bukkit.entity.[name] entities from SafeZone entity removal.
    # Examples:
    # "Arrow", "Animals", "EnderDragon", "EnderPearl", "Fish", "IronGolem", "Pig",
    # "Projectile", "ThrownPotion", "TNTPrimed", "Snowball"
    ExemptEntityTypes: []

    # If you turn DechargeEE on, then
    # - All EE items specified in the ModModifications config will be decharged
    #   in SafeZones
    # Default: true
    DechargeEE: true

    # If you turn DisableRingOfArcana on, then
    # - When someone is in a SafeZone with a ring of arcana, it will always be set
    #   to "Earth" mode and it will be turned off.
    # Default: true
    DisableRingOfArcana: true

    # If you turn DisableFlying on, then
    # - All flying items will be disabled when you are in a SafeZone.
    # DisableFlying: false
    # This feature does not work (yet).

# If TekkitRestrict should use native safezones (better performance)
# Add them with /tr admin safezone addnative <x1> <z1> <x2> <z2> <name>
# Default: true
UseNativeTekkitRestrictSafezones: true

# The plugins TekkitRestrict should use to make safezones.
#
# There is only basic support for Factions, Towny and PreciousStones.
# This means that all land claimed by a faction, a town, etcetera is a safezone.
# Players with the build/destroy permission for that land will bypass it.
#
# For GriefPrevention, you can choose different modes (See below).
# For WorldGuard, you can specify per region if it should be a safezone. You can
# compare this mode with the "Specific" mode of GriefPrevention.
# Default: true for all
SSEnabledPlugins: 
    GriefPrevention: true
    WorldGuard: true
    Factions: true
    Towny: true
    PreciousStones: true

##########################################################################################
############################ GriefPrevention Specific settings ###########################
##########################################################################################

# If someone is a manager in a claim, the SafeZone will not apply for him.
# (If you would like a setting to turn this on or off, please make a feature request
# ticket on the Bukkit Dev TekkitRestrict page.)

# GriefPrevention SafeZone Method
# Can be "All", "Admin", "Specific" or "SpecificAdmin"
# "All": All GriefPrevention claims are SafeZones.
# "Admin": All GriefPrevention admin claims are SafeZones. (Default)
# "Specific": You can specify per claim if you want it to be a SafeZone.
# "SpecificAdmin": Only admin claims can be SafeZones, but you can specify it per claim.
GriefPreventionSafeZoneMethod: "Admin"

##########################################################################################
############################## WorldGuard Specific settings ##############################
##########################################################################################

# WorldGuard SafeZone Method
# Can be "All" or "Specific"
# "All": All WorldGuard regions are SafeZones.
# "Specific": You can specify per region if you want it to be a SafeZone. (Default)
WorldGuardSafeZoneMethod: "Specific"

##########################################################################################